# TODO ADD YOUR CODE HERE 
name: Deployer for Churn Model

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout SVC
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build Docker Image
      run: docker build --no-cache -t churn_model_image .
    
    - name: Run Model
      run: docker run churn_model_image python /src/run_model.py 1 2 3 4 5 6 7 8
